language: node_js

nodejs:
  - "8"

install: npm install

script:
  - npm run test:unit
  - npm run test:e2e:sauce
  - npm run codecov
  - npm run doc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master

addons:
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_ACCESS_KEY
