export { argToKey } from './utils/assist'
export { default as promiseMemoryCache } from './cache/promise-mm'
export { default as promiseSessionStorageCache } from './cache/promise-ss'
export { default as pureFuncMemoryCache } from './cache/pure-func-mm'
export { clearCache } from './cache/store'
