export { argToKey } from './utils/assist'
export promiseMemoryCache from './cache/promise-mm'
export promiseSessionStorageCache from './cache/promise-ss'
export pureFuncMemoryCache from './cache/pure-func-mm'
export { clearCache } from './cache/store'
